package vista;

import javax.swing.JOptionPane;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

import comun.Entidad;
import comun.Operacion;
import comun.RetoException;
import controlador.Interprete;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gsalinas
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI(Interprete interprete) {
        this.interprete = interprete;
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                interprete.listo();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        comando = new javax.swing.ButtonGroup();
        entidad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        crear = new javax.swing.JRadioButton();
        recuperar = new javax.swing.JRadioButton();
        actualizar = new javax.swing.JRadioButton();
        eliminar = new javax.swing.JRadioButton();
        cliente = new javax.swing.JRadioButton();
        capitan = new javax.swing.JRadioButton();
        alquiler = new javax.swing.JRadioButton();
        ligero = new javax.swing.JRadioButton();
        transporte = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        solicitud = new javax.swing.JEditorPane();
        ejecutar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        respuesta = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evaluador Reto 5");
        setMinimumSize(new java.awt.Dimension(1280, 720));

        comando.add(crear);
        crear.setSelected(true);
        crear.setText("Crear");

        comando.add(recuperar);
        recuperar.setText("Recuperar");

        comando.add(actualizar);
        actualizar.setText("Actualizar");

        comando.add(eliminar);
        eliminar.setText("Eliminar");

        entidad.add(cliente);
        cliente.setText("Cliente");

        entidad.add(capitan);
        capitan.setText("Capitán");

        entidad.add(alquiler);
        alquiler.setText("Alquiler");

        entidad.add(ligero);
        ligero.setText("Vehículo Ligero");

        entidad.add(transporte);
        transporte.setSelected(true);
        transporte.setText("Vehículo Transporte");

        jScrollPane1.setViewportView(solicitud);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(recuperar)
                                                        .addComponent(actualizar)
                                                        .addComponent(eliminar)
                                                        .addComponent(crear))
                                                .addGap(247, 247, 247)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(alquiler)
                                                        .addComponent(transporte)
                                                        .addComponent(ligero)
                                                        .addComponent(capitan)
                                                        .addComponent(cliente))
                                                .addGap(0, 736, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crear)
                                        .addComponent(ligero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(recuperar)
                                        .addComponent(transporte))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(actualizar)
                                        .addComponent(cliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(eliminar)
                                        .addComponent(capitan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alquiler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        ejecutar.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        ejecutar.setForeground(new java.awt.Color(51, 51, 255));
        ejecutar.setText("Ejecutar !!!");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        respuesta.setEditable(false);
        jScrollPane2.setViewportView(respuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addComponent(ejecutar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ejecutar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (mapper == null) {
            mapper = new ObjectMapper();
        }

        try {
            if (defaultContent == null) {
                defaultContent = mapper.readTree(
                        "{\"vehiculo\":{\"matricula\":1,\"nombre\":\"Halcón Milenario\",\"velocidad\":75,\"longitud\":34.37},\"tripulantes\":4,\"pasajeros\":6}");
            }
            if (solicitud.getText().isEmpty()) {
                showMessage();
                return;
            }

            JsonNode json = mapper.readTree(solicitud.getText());
            solicitud.setText(json.toPrettyString());
            respuesta.setText(
                    mapper.readTree(
                            interprete.procesarComando(
                                    crear.isSelected() ? Operacion.CREAR
                                            : recuperar.isSelected() ? Operacion.RECUPERAR
                                                    : actualizar.isSelected() ? Operacion.ACTUALIZAR
                                                            : Operacion.ELIMINAR,
                                    ligero.isSelected() ? Entidad.LIGERO
                                            : transporte.isSelected() ? Entidad.TRANSPORTE
                                                    : cliente.isSelected() ? Entidad.CLIENTE
                                                            : capitan.isSelected() ? Entidad.CAPITAN : Entidad.ALQUILER,
                                    json.toString()))
                            .toPrettyString()

            );
        } catch (RetoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            ObjectNode error = mapper.createObjectNode();
            error.put("mensage", ex.getMessage());
            if (ex.getCause() != null) {
                error.put("causa", ex.getCause().getMessage());
            }
            int count = 0;
            for (StackTraceElement st : ex.getStackTrace()) {
                error.put("stackTrace " + (++count), st.toString());
            }
            respuesta.setText(error.toPrettyString());

        } catch (Exception ex) {
            showMessage();
        }
    }

    private void showMessage() {
        JOptionPane.showMessageDialog(null, "Solicitud Inválida");
        solicitud.setText(defaultContent.toPrettyString());
    }

    /**
     * @param args the command line arguments
     */
    public static void start(Interprete interprete) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI(interprete).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton actualizar;
    private javax.swing.JRadioButton alquiler;
    private javax.swing.JRadioButton capitan;
    private javax.swing.JRadioButton cliente;
    private javax.swing.ButtonGroup comando;
    private javax.swing.JRadioButton crear;
    private javax.swing.JButton ejecutar;
    private javax.swing.JRadioButton eliminar;
    private javax.swing.ButtonGroup entidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton ligero;
    private javax.swing.JRadioButton recuperar;
    private javax.swing.JEditorPane respuesta;
    private javax.swing.JEditorPane solicitud;
    private javax.swing.JRadioButton transporte;
    // End of variables declaration
    private ObjectMapper mapper;
    private JsonNode defaultContent;
    private Interprete interprete;
}
